apiVersion: eventing.k8s.neuroglia.io/v1alpha1
kind: Channel
metadata:
  name: natss-channel
  namespace: neuroglia-eventing
  labels:
    name: natss-channel
spec:
  container: 
    name: natss-channel
    image: neuroglia.io/eventing/channels/natss:1.0
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
      name: http
    env:
    - name: NATSS__CLUSTERID
      value: neuroglia-eventing
    - name: NATSS__HOST
      value: nats://nats-streaming.natss.svc.cluster.local:4222
    startupProbe:
      httpGet:
        path: /healthz
        port: http
      failureThreshold: 30
      periodSeconds: 5
    readinessProbe:
      httpGet:
        path: /healthz
        port: http
      failureThreshold: 30
      periodSeconds: 5
    livenessProbe:
      httpGet:
        path: /healthz
        port: http
      initialDelaySeconds: 3
      periodSeconds: 3