apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: channels.eventing.k8s.neuroglia.io
spec:
  group: eventing.k8s.neuroglia.io
  subresources:
    status: {}
  versions:
    - name: v1alpha1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: channels
    singular: channel
    kind: Channel

---

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: brokers.eventing.k8s.neuroglia.io
spec:
  group: eventing.k8s.neuroglia.io
  subresources:
    status: {}
  versions:
    - name: v1alpha1
      served: true
      storage: true
  additionalPrinterColumns:
    - name: Channel
      type: string
      description: The broker's channel
      JSONPath: .spec.channel
    - name: Url
      type: string
      description: The url of the broker's service
      JSONPath: .status.url
  scope: Namespaced
  names:
    plural: brokers
    singular: broker
    kind: Broker

---

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: subscriptions.eventing.k8s.neuroglia.io
spec:
  group: eventing.k8s.neuroglia.io
  subresources:
    status: {}
  versions:
    - name: v1alpha1
      served: true
      storage: true
  additionalPrinterColumns:
    - name: Id
      type: string
      description: The subscription's id
      JSONPath: .spec.id
    - name: Channel
      type: string
      description: The channel the subscription is bound to
      JSONPath: .spec.channel
    - name: Subject
      type: string
      description: The CloudEvent subject the subscription applies to
      JSONPath: .spec.subject
    - name: Type
      type: string
      description: The CloudEvent type the subscription applies to
      JSONPath: .spec.type
    - name: Source
      type: string
      description: The CloudEvent source the subscription applies to
      JSONPath: .spec.source
    - name: IsDurable
      type: boolean
      description: A boolean indicating whether or not the subscription is durable
      JSONPath: .spec.durable
  scope: Namespaced
  names:
    plural: subscriptions
    singular: subscription
    kind: Subscription

---