apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: subscriptions.eventing.k8s.neuroglia.io
spec:
  scope: Namespaced
  names:
    plural: subscriptions
    singular: subscription
    kind: Subscription
  group: eventing.k8s.neuroglia.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              type: object
              required: 
                - id
                - channel
              properties:
                id:
                  type: string
                offset:
                  type: integer
                  minimum: -1
                channel:
                  type: string
                filter:
                  type: object
                  properties:
                    attributes:
                      type: object
                subscribers:
                  type: array
                  items:
                    type: object
                    required:
                      - url
                    properties:
                      url:
                        type: string
                      mode:
                        type: string
                        default: LoadBalanced
                        enum:
                          - LoadBalanced
                          - Headless
      additionalPrinterColumns:
        - name: Id
          type: string
          description: The subscription's id
          jsonPath: .spec.id
        - name: Channel
          type: string
          description: The channel the subscription is bound to
          jsonPath: .spec.channel
        - name: Subject
          type: string
          description: The CloudEvent subject the subscription applies to
          jsonPath: .spec.subject
        - name: Type
          type: string
          description: The CloudEvent type the subscription applies to
          jsonPath: .spec.type
        - name: Source
          type: string
          description: The CloudEvent source the subscription applies to
          jsonPath: .spec.source
      subresources:
        status: {}
  