name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file src/Gateway/Neuroglia.K8s.Eventing.Gateway.Api/DockerFile --tag eventing/gateway:1.0
